### ISSUE TITLE
AWS Playground - Failed to update swap chain

### ISSUE THREAD

**Issue by radwaverf** [nvidia-holoscan/holohub#394] opened 2024-06-21 01:49 UTC
I tried going through Holoscan Playground on AWS, and I'm hitting an error with this section:
https://github.com/nvidia-holoscan/holohub/tree/main/tutorials/holoscan-playground-on-aws#video-replayer-example

![image](https://github.com/nvidia-holoscan/holohub/assets/47957763/2c57aa78-b591-4013-91d6-6e8c31bf0f14)

The device memory though appears to have very limited utilization at its peak
![image](https://github.com/nvidia-holoscan/holohub/assets/47957763/bfb137bc-3799-4d55-ac5c-3e804b131751)

From what I can tell, this error is happening from here:
https://github.com/nvidia-holoscan/holoscan-sdk/blob/main/modules/holoviz/src/vulkan/framebuffer_sequence.cpp#L103-L119
which has a note about driver 510 having issues, but I'm using driver 550.54.15. I haven't tried going into a debugger yet to see what width/height/dimensions are, but I'm wondering if somehow those values are excessively large that could cause an out of memory issue here. The non-graphical parts of the tutorial seem to be working ok.

**Comment by Smart-Surgery-Eason** [comment] 2024-06-25 05:00
@radwaverf I friend. I encountered the same issue as you. any update?

**Comment by AndreasHeumann** [comment] 2024-06-25 07:50
Hi, there was a regression with 545 and 550 drivers which can cause that error. Updating to 555 or downgrading to 535 drivers should fix that issue. Let me know it this solved your problem.

**Comment by Smart-Surgery-Eason** [comment] 2024-06-26 02:57
Thanks a lot, man. 535 driver works for me~

**Comment by AndreasHeumann** [comment] 2024-06-26 05:43
Thanks, closing the issue.

**Closed by AndreasHeumann** 2024-06-26 05:43 UTC
